# We use the 'devcontainers' image as our base.
# This solves the user conflict because user 'vscode' already exists here.
# It also includes Git, curl, and Oh-My-Zsh automatically.
FROM mcr.microsoft.com/devcontainers/dotnet:10.0